version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: jsonplaceholder-postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-jsonplaceholder}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsonplaceholder-api
    restart: always
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/jsonplaceholder}
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-1d}
      PORT: ${PORT:-3000}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
